version: '3'

services:
  nginx-container:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8000:80"
  naxsi-container:
    build:
      context: ./naxsi/
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:4000:80"